### ISSUE TITLE
TrackInfo 페이지 구현

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#107]
### Requirement
- 선택된 트랙에 대한 정보를 보여주는 페이지
- 주요 정보
  - 트랙 정보 (곡명, 래퍼명, 가사 등등)
  - Feedback 정보(Quick or Premium)
  - 좋아요/공유하기 
  - 아티스트가 올린 다른 곡 리스트 *\*  
  - 리릭비디오 링크 (if available) **
  - 업로드 날짜 **
### Issue
- 위의 정보들을 어떻게 보여줘야 할 지에 대해서는 논의가 필요

**Comment by good2hear** [comment]
위에다가 추가하겠습니당

**Comment by good2hear** [comment]
구현완료
