### ISSUE TITLE
iOS에서 여러곡 재생시 앱이 뻗음

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#110]
### Issue Description
- iOS에서 perf monitor 로 확인해 보면 곡을 재생할 때마다 메모리가 계속 쌓임. 
- 메모리 누수인지 확인 필요
### Steps to Reproduce

Step 1: 앱 실행 후 곡 재생
Step 2: 다음 곡 재생
Step 3: 2번 반복
### Expected Results

메모리 변화가 크게 변화 없어야 함
### Actual Results

곡을 재생 할 때마다 메모리 사용량 증가

**Comment by good2hear** [comment]
- Timer 를 NSTimer -> addperiodictimeobserverforinterval 로 변경 
- 속도 빨라졌고 메모리 변화도 많이 줄어듬
- 계속해서 테스팅 해보고 status update 예정
