### ISSUE TITLE
Designer Requirements

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#116]
댓글로 달아주셈

**Comment by orgpark** [comment]
힙합사랑하는 사람

**Comment by orgpark** [comment]
명예의전당 Thumbnail. NBF2 네임택 스타일이 될 수도 있고

**Comment by good2hear** [comment]
차트 디자인 심플함은 유지하면서 좀 더 swag 있게 (예: 좋아요 버튼 -> Respect or Swag)

**Comment by orgpark** [comment]
몇몇 artwork 작업도 가능한지 봐야 함

**Comment by orgpark** [comment]
2016/10/14에 협의된 사항
1. 플레이어 메인에서는 앨범자켓, 좋아요 버튼, 좋아요 수를 보여준다.
2. 앨범자켓 터치하면 피드백, 가사, request_msg등을 한방에 스크롤 하는 형태로 보여준다. (tab 없음) —> play, next, previous 버튼등의 콘트롤은 살리고 나머지 화면을 가득 채워서
3. 피드백 점수는 Elevate 느낌으로 가면 좋겠다.

**Comment by orgpark** [comment]
컨셉은 터널 싸이퍼. 검정색화면 느낌으로 진행.
앨범 커버는 흑백으로 변경해버리는것도 고려. 해보고 아니면 다시 컬러로.
컬러로 가더라도 우리 컨셉에 맞게 약간의 필터 적용하는것도 괜찮을 듯 함.

**Comment by kyo504** [comment]
작업해야 할 화면
- 홈 페이지
- 검색 페이지
- 곡 올리기 페이지
- 액티비티 페이지
- 아티스트 페이지
- 곡 정보 페이지
- 옵션(설정) 페이지
- 재생목록 페이지

**Comment by orgpark** [comment]
11월 1주차에 디자이너로부터 받아야 하는 내용
* 플레이어 페이지
* 플레이어 상세보기 페이지 (텍스트)
* 아티스트 페이지
* 재생목록 페이지
