### ISSUE TITLE
StatusBar와 UI 겹침

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#134]
### Issue Description

StatusBar 와 UI가 겹친다.
### Steps to Reproduce

Step 1: 앱 실행
Step 2: 로그인 후 Main 화면 진입
### Expected Results

탭 리스트와 상단 StatusBar가 겹치지 않아야 한다.
### Actual Results

텍스트와 StatusBar UI가 겹치게 표기된다.
### Additional Information

Android와 달리 iOS는 Screen의 시작이 StatusBar를 포함한다. 그래서 화면 패딩을 줄 때 이 부분을 고려해야 한다.

**Comment by good2hear** [comment]
구현완료
