### ISSUE TITLE
아티스트 검색시에 rap name 으로만 가져오는 것으로 보임

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#138]
### Issue Description
- 아티스트 검색시에 rap name으로만 검색되는 것 같음
- rap name이 null인 경우에는 검색되지 않음
- rap name 혹은 username으로 부터 검색 결과를 가져와야 할 듯

### Steps to Reproduce

Step 1: 앱 실행 후 검색 페이지
Step 2: HUN으로 검색

### Expected Results
내가 검색 되어야 함

### Actual Results
검색 결과가 없음

**Comment by kyo504** [comment]
@orgpark 이거 확인 좀 부탁해~

**Comment by orgpark** [comment]
rap_name 이 있다는 이야기는 곡을 한개라도 올린경우. null인경우는 일반 listener이기 때문에 검색이 안되는것이 오히려 자연스러울 수 있다고 보임. 필요하다면 다른 attribute에 대해서도 검색 추가는 가능하지만 현재 수준은 이정도로 일단은 적당해 보임
