### ISSUE TITLE
Play 횟수 카운팅

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#144]
Play 횟수를 카운팅

서버API 제작 후 front end에서 곡이 load 될때마다 API 호출
SoundCloud의 playback_count 대신 우리만의 playback_count 사용. (프론트에서는 변경내용 없음)

API Requirements:
- 곡 id
- user id
- device 정보 혹은 UserAgent String (웹의 경우)
- user token

**Comment by orgpark** [comment]
곡이 로드될때마다 아래의 API 불러주셈
* post /api/v1/increment_playback_count
  - request parameters: { :device_info, :song_id }
  - return values: {:playback_count}

**Comment by kyo504** [comment]
@orgpark `device_info`는 어떤걸 넘겨줘야해?

**Comment by kyo504** [comment]
완료
