### ISSUE TITLE
재생 전에 해당 곡이 유효한지 확인

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#147]
### Requirements
- 사이트에 올라온 곡 중에서 SoundCloud에서 곡을 삭제한 경우 해당 URL이 유효하지 않음
- 현재 앱에서는 무조건 플레이어에 해당 링크를 던지는데 유효하지 않는 링크이기 때문에 곡 재생이 안 되고 멈춰있음
- 재생 전에 사운드 클라우드 링크로 핑을 보내서 유효한 경우에만 플레이를 한다.

**Comment by kyo504** [comment]
완료

**Comment by orgpark** [comment]
지금 생각난건데 만약 유효하지 않다면 서버에 이 곡은 유효하지 않다고 알려주면 좋을 듯. 오늘 API 만들겠음

**Comment by orgpark** [comment]
그러면 다른 클라이언트는 그 곡이 아예 뜨지 않도록 될 수 있을 듯

**Comment by orgpark** [comment]
* get /api/v1/rid_of_nonstreamable DONE
  - request parameters: { :id (of the song) } 
  - return values: song 정보

**Comment by kyo504** [comment]
완료
