### ISSUE TITLE
Server API 추가 - 곡 등록하기

### ISSUE THREAD

**Issue by good2hear** [AllThatSeries/fym_mobile#156]
### Issue Description

Publish 페이지에서 곡 등록하기를 눌렀을 때의 서버 API 추가
### Expected Results

곡 등록하기 눌렀을 때 웹에서와 마찬가지로 곡 등록하기 작동

**Comment by orgpark** [comment]
* post /api/v1/request_quick_feedback
  - request parameters: { :title, :rap_name, :email, :sc_link, :lyrics_text, :location }
  - return values: 성공시 곡정보, 실패시 :error

**Comment by orgpark** [comment]
input validation check하는 코드는 아래와 같음.
frontend에서 최대한 서버에 요청없이 테스트하면 좋을 듯.
다만 sc_link의 포맷은 프론트엔드에서 테스트하고 uniqueness테스트는 서버를 통하지 않으면 안되기 때문에 그 부분은 서버에 요청할때 테스트하는걸로.

before_save { self.email = email.downcase }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
SOUNDCLOUD_REGEX = /(https:\/\/soundcloud.com|snd.sc|https:\/\/w.soundcloud.com)\/(.*)/
validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
validates :rap_name, presence: true
validates :title, presence: true
validates :sc_link, presence: true, uniqueness: true, format: { with: SOUNDCLOUD_REGEX }
validates :lyrics_text, presence: true, length: { minimum: 100 }
validates :request_msg, presence: true, length: { minimum: 7 }

**Comment by good2hear** [comment]
구현 완료
