### ISSUE TITLE
피드백 주는 기능

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#161]
publish와 비슷한 형태로 가면 됨. API 준비 후 front end에서 반영

two step 으로 진행해야 함.
1. instructor인 경우에는 인스트럭터 정보와 피드백 할 수 있는 버튼을 UI상으로 제공 (my_instructor_info API 이용) --> 현재 만들어서 반영하였음
2. 실제 피드백하기 버튼 눌렀을 때, publish page와 비슷한 모양으로 동작하게... (API 제공 예정)

**Comment by orgpark** [comment]
선생이 피드백을 주는 위치 고민 필요

**Comment by orgpark** [comment]
my_info에 instructor 정보 넣을지, is_instructor API를 call할 지... 결정 필요. 일단 둘다 여는 것으로...

**Comment by orgpark** [comment]
아래의 API를 token 값을 가지고 요청하면 됨. 완료된 곡은 최근 10개만 내려주는 형태로 일단 구현했음.

* get /api/v1/my_instructor_info DONE
  - return values: {:instructor_id, :name, :image_url, :email, :coins, :cashouts[{:id, :date, :coins}], :incomplete_songs[], :completed_songs[10]}

Test용 토큰들 (토큰이 짧은건 SC, 긴건 FB):
* 인스트럭터가 아닌경우 test를 위해서는 본인의 토큰 그냥 이용하면 되고
* 인스트럭터인 경우의 토큰들
  - 박현택 선생테스트: 1-112420-117734714-ef5b18195abc7
  - 유현: EAAPzhN73yQMBAGjrYKScy8nIGtRsOYrBJczlpJqabZALWHKLDQJUlcYTW8hcNoWc9Bbq7r038IGLsEiZAZAJpLmKZA0xhQ4J94IXkEfYLIZByXeiGnZB9uaMWn7iZCnIbCbcT73YnuRte1m6XMXMfxr6ZB9DwGD0eCjWaYLNZCSDJ2r5PTXU7ZBTjmwRIDf0DKJyYAzhR7MtwnOZCGwSuQBe1nK
  - REFLOW: 1-112420-28324447-ebf6b51fb7cefc
  - BLACK NINE: EAAPzhN73yQMBABdZC6StKhKooETOuwfKfNyLZAPpZB0io6uZAZApP1d4vQM4Mwfo2fXdZBx0RDQhZB6lQt6xxZAMrZC3klxKrnLkehNY96upcTecpXZCvTgXVnEudDobFdPBaZBw29asAqDUJ1K6A8hMAPkEjY4M3n69NWajXhuewhmXtbNTeAlZBbVdsHulKl8uAS0P2ElNAcqrLgZDZD
  - 김아무게: EAAPzhN73yQMBANvmdw1abT30TH36zDtX1cN9fqwibOYdkY7ipkaECoz5BLmvLgIkKdPXBggMbs8rn1N21ZBfwhUwozO7LNqMx1LCzIBeINQ4FOtOXslm61VOpmVvZBChezivDCgwL3vpl0Pw9ErtGh5mypMTSh9Xfu6af59hH5urYVZBl4diGgZCy9lMZBDER0qZCco2zWuZC8ZC1lRNCh78
  - 격: EAAPzhN73yQMBAEeqGMKA3EZCHCvBqbeXzMbwywsTXggzoHLnobmzLMIrZCAZBm0a7AQ5TbjderEXWZAnj4s0CTqbvNpF5ZAazyZAmqyrM3tDrP1qZAbxFfOqWe1dZAWVCDuZBIgq8OOKxCc2HI6wfObB4OsYJKZAGxtV3EMsw7KVm1JwJOpGYSZB6Jv0HoZCtRNhQdRQY6kYMRRSQgZDZD

**Comment by orgpark** [comment]
요구사항:
1. 완료 안된거에는 더보기 없어야 함
2. 제목과 래퍼명 나와있는 부분에 언제 요청된건지 나와야 함. (today, 1 day ago, 2 days ago)

![image](https://cloud.githubusercontent.com/assets/3348009/20663260/2c3629be-b59a-11e6-95ca-dbf8737fc662.png)

**Comment by good2hear** [comment]
구현완료
