### ISSUE TITLE
License Information 페이지 구현

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#167]
### Requirements
- SoundCloud Pulse 앱에 있는 내용을 참고해서 만들면 될 듯

**Comment by orgpark** [comment]
Settings의 한 섹션에 SoundCloud Pulse 앱 참고해서 비슷하게 혹은 완전히 같은 포맷으로 적어놓으면 될 듯.

**Comment by kyo504** [comment]
완료
