### ISSUE TITLE
license 파일 자동 생성 기능

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#174]
### Requirements
- License 내용을 파싱해서 파일로 저장
- LicenseView에서는 해당 파일을 로드해서 `dataSource`로 사용
- 새로 패키지가 추가될 때마다 코드 작성 필요없이 툴을 돌려서 `license.json`파일을 생성해서 기존 파일 overwrite

**Comment by orgpark** [comment]
이거 나이수!

**Comment by kyo504** [comment]
완료
