### ISSUE TITLE
Set Track URL logic 을 바꿀 필요가 있음

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#180]
play 되던 곡이 플레이가 안되는 경우가 두가지 경우임
1. URL을 바꿨거나
2. 지웠거나

1번의 경우에는 stream url이 바뀌지 않는것으로 확인됨.
즉 url을 바꿨어도 valid한 stream url이 있다면 그냥 두도록 해야 함.

**Comment by orgpark** [comment]
stream url 이 valid한지만 check하는 로직 서버단에도 적용 필요

**Comment by orgpark** [comment]
@kyo504 참고
* header의 status code를 체크하면 됨.
* stream_url 은 기본적으로 redirection이 되기 때문에 302 코드를 던지게 됨.
* 302 코드를 던지는 녀석은 valid한 stream_url이라고 볼 수 있음

**Comment by orgpark** [comment]
@kyo504 
아니면 엄청 쉽게 해결될 수도 있음. 아래처럼 stream_url이 동작하지 않는 경우에는 404에러를 뿌려버림. Player자체에서 stream_url이 404일경우 위로 어떤식으로든 이벤트를 던져주면 그에 따라 다음 동작을 결정할 수 있다면? ㅎㅎ

![image](https://cloud.githubusercontent.com/assets/3348009/20003579/9cdf8cba-a2ca-11e6-945d-3554533c8c42.png)

**Comment by kyo504** [comment]
@orgpark 근데 이게 실패했을 때가 아니라 유효한 경우가 문제라서...

**Comment by orgpark** [comment]
여튼 확실한건 헤더만 빨아오는 콜은 데이터 받아오는것보다 많이 빠르긴 함.
