### ISSUE TITLE
iOS 에서 player 동작 이슈

### ISSUE THREAD

**Issue by good2hear** [AllThatSeries/fym_mobile#186]
### Issue Description
iOS 에서 player 실행 시 재생, 다음곡, 이전곡 넘어가는 속도가 매우느림
오히려 예전보다 훨씬 더 느려짐

### Steps to Reproduce

Step 1: iOS device 혹은 simulator 로 앱 실행 
Step 2: playlist 에 있는 아무곡이나 실행
Step 3: 이전곡, 다음곡 재생 

### Expected Results
1. playlist 에 있는 곡 실행하면 player 화면으로 넘어가서 바로 play 시작
2. 이전곡, 다음곡을 누르면 바로 넘어가서 play 

### Actual Results
playlist 에 있는 곡을 처음 누르면 play 하기까지 5-10초가량 시간 소요 (device, simulator 모두)
이전곡, 다음곡을 눌러도 5-10초 이상 걸려서 곡 재생

### Additional Information
Timer 쪽 문제인지 다른쪽 문제인지 알아봐야함

**Comment by kyo504** [comment]
Stream URL의 validity 체크 할 때 스트림 정보를 모두 받고 response를 보내줘서 오래 걸림. Header 정보만 바로 받도록 수정함
