### ISSUE TITLE
업데이트 종용 수단

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#187]

**Comment by orgpark** [comment]
Pop up 띄우는 형태로 진행

**Comment by orgpark** [comment]
API 생성 필요함.

**Comment by orgpark** [comment]
ios는 http://itunes.apple.com/lookup?id=331177714 같은 get API를 쓰면 버전등의 앱 디테일 정보를 받아올 수 있지만 안드로이드의 경우에는 official api를 제공하고 있지 않기 때문에 위험이 있음. 매번 들어갈 때마다 앱 버전을 체크하기보다는 앱의 버전 정보를 우리 서버에 기록하고 이에 대해서 true, false 값과 app을 업데이트할 수 있는 url을 함께 내려주는 API를 만드는 편이 좋을 듯 함.

일단은
/api/v1/check_updates 으로 뚫어놓았음.
parameters: {:device_info, :version_no}
device_info = 'android' or 'ios'

example 
(현재 0.0.2를 일단 최신으로 해 놓은 상태)
http://feedyourmusic.com/api/v1/check_updates?device_info=ios&version_no=0.0.2
{
"update_available": false,
"latest_version": "0.0.2",
"update_url": "https://itunes.apple.com/app/starbucks/id331177714"
}

* get /api/v1/check_updates
  - request parameters: {:device_info, :version_no} //device_info = 'android' or 'ios'
  - return values: {:update_available, :latest_version, :update_url}
}

**Comment by orgpark** [comment]
@kyo504, @good2hear  실제 적용 완료되면 이슈 닫아주셈.

**Comment by kyo504** [comment]
저 API를 로그인 성공 할 마다 하면 되나?

**Comment by orgpark** [comment]
로그인 성공이라는건 자동 로그인될때도 마찬가지이지?

**Comment by kyo504** [comment]
ㅇㅇ 마찬가지

**Comment by orgpark** [comment]
그렇게 하면 되지 않을까 싶음

**Comment by kyo504** [comment]
@orgpark 현재 앱 버전이 더 높은데도 계속 `update_unavailable`이 `true`로 오는 것 같아.

**Comment by kyo504** [comment]
적용 완료
