### ISSUE TITLE
prev/next 버튼 눌렀을 때 동작

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#206]
### Issue Description
로딩시간이 있기 때문에 prev/next 눌렸는지 안눌렸는 지 알 수가 없음.

### Steps to Reproduce

Step 1: next/prev 누름

### Expected Results
버튼을 누르면 pause혹은 stop을 바로 시키고 다음곡 로드하면 더 좋을 듯 함.

### Actual Results
버튼이 누르면 몇초 후 다음곡/이전곡 재생됨

**Comment by good2hear** [comment]
이게 시뮬레이터에서 돌릴땐 로딩시간이 그리 안긴데, 확실히 아이폰에서 직접 돌려보니 좀 느린감이 있네요.

**Comment by kyo504** [comment]
수정 완료
