### ISSUE TITLE
아티스트 페이지 gui 이슈

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#234]
### Issue Description
1. 상단 화면 내부 아이템들 배치가 상단에 치우쳐져 있음
2. 더보기 버튼 색상 변경 필요
3. Follow 버튼 안 보임
### Steps to Reproduce

Step 1: 앱 실행
Step 2: 아티스트 페이지 진입

### Expected Results
1. 페이지 레이아웃이 가이드에 맞아야 함
2. 버튼 색상이 'paleRed'이어야 함
3. Follow 버튼이 있어야 함

### Actual Results
1. 가이드와 다르게 배치됨
2. 더보기 버튼이 흰색임
3. Follow 버튼 없음

**Comment by good2hear** [comment]
완료
