### ISSUE TITLE
아티스트 정보에서 보여지는 곡 수가 적음

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#261]
### Issue Description
- 현재 최대 3곡만 보여주는데 너무 적다고 생각 됨
- 참고로 벅스는 7곡, 애플뮤직은 8곡, 멜론/지니는 다 보여줌

### Sugesstion
- 최소 5곡에서 8곡사이가 좋을 것 같음

**Comment by good2hear** [comment]
그럼 해당 아티스트의 곡만 5~8곡 보여주는건 어떨까요?
멘토의 경우 피드백 준 곡과 좋아요 누른 곡까지 5~8곡 다 보여지게 되면 너무 길어질수도 있을 것 같네요

**Comment by kyo504** [comment]
'ScollView' 를 사용하는 이유는 사용자에게 볼 수 있는 내용이 더 있기때문이기에 내용이 어느 정도 길어지는 거에 대해서는 큰 문제는 없다고 보여지고 난 각 섹션마디 5곡은 있으면 좋겠어

@orpark 의견 부탁해

**Comment by good2hear** [comment]
5곡씩은 괜찮을거 같습니다~ 
8곡으로 멘토 아티스트 페이지 생각했을 때 24곡 스크롤을 생각해서 길어보였는데, 멘토가 그리 많지도 않구요.

**Comment by orgpark** [comment]
멘토가 완료한 피드백들에 대해서 pagination을 통해 전체를 나눠서 내려주는 API 필요

**Comment by orgpark** [comment]
9곡으로 감!

**Comment by good2hear** [comment]
완료
