### ISSUE TITLE
곡정보에서 아티스트 정보 들어가면 앱 크래시

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#263]
### Issue Description
- 곡 정보에서 아티스트를 누르면 앱이 뻗는다

### Steps to Reproduce

Step 1: 앱실행 후 
Step 2: 금방올께 곡정보로 진입
Step 3: 아티스트 누름

### Expected Results
아티스트 페이지로 이동해야함

### Actual Results
앱 뻗음

**Comment by good2hear** [comment]
student_id 대신에 mentor_id 로 param 을 보냈었네요~
바꾸니까 고쳐졌습니다. artistView 수정하면서 같이 고쳐서 commit 하겠습니다

**Comment by kyo504** [comment]
이슈는 커밋하고 pr이 완료되면 닫아줘

**Comment by good2hear** [comment]
넵!

**Comment by good2hear** [comment]
완료
