### ISSUE TITLE
곡정보에서 담기 누르면 동작에 대한 결과를 알 수 없음

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#265]
### Issue Description
- 곡정보에서 담기를 누르면 동작에 대한 피드백이 없음
- 벅스는 미니 플레이어의 재생목록에 배지가 생겼다가 사라짐
- 멜론은 토스트가 띄어져서 곡이 재생목록에 추가 되었음을 알려줌

### Steps to Reproduce

Step 1: 아무 곡정보 페이지
Step 2: 담기 버튼 누름

### Expected Results
- 곡이 정상적으로 추가되었음을 열려주는 피드백이 보였으면 함

### Actual Results
- 아무런 피드백이 없음

**Comment by kyo504** [comment]
토스트를 띄우는 것으로 함

**Comment by good2hear** [comment]
완료
