### ISSUE TITLE
현재 구현된 공유 기능 변경

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#275]
### Issue Description
- 현재 공유가 fbsdk를 이용한 공유여서 페북에만 공유가 됨 (다른 앱으로 공유할 수 없음)

### Suggestion
- RN의 Share 기능을 통해서 구현 필요

**Comment by kyo504** [comment]
@orgpark @good2hear 난 RN의 Share 통해서 플랫폼의 Share 기능을 이용해서 구현 하는 것이 좋을 것 같은데 의견 남겨줘.

**Comment by good2hear** [comment]
넵 저도 RN Share 로 하는게 좋을 것 같습니다.
