### ISSUE TITLE
아티스트 정보에서 Follow 버튼 누르면 버튼 누르고 있으면 뒷 부분이 가려짐

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#300]
### Issue Description
아티스트 정보에서 Follow 버튼 누르면 버튼 뒷부분이 가려짐

### Steps to Reproduce

Step 1: 앱 실행
Step 2: 아티스트 정보 페이지 진입
Step 3: Follow 버튼 누름

### Expected Results
뒷 부분이 가려지는 현상 없어야 함

### Actual Results
깜빡임이 발생하면서 버튼 뒷부분 화면을 덮음

**Comment by good2hear** [comment]
완료
