### ISSUE TITLE
곡올리기 GUI 이슈

### ISSUE THREAD

**Issue by kyo504** [AllThatSeries/fym_mobile#308]
### Issue Description
- 가사의 placeholder에 가사를 100자 입력해달라고 했으면 좋겠음 (뭘 100자 입력하라는지 인지라기 어려움)
- 플레이스 홀더가 중앙에 왔으면 좋겠음
- 곡 설명 부분 높이가 텍스트 컨텐츠만큼 업데이트 되었으면 좋겠음
- 죄측 아이콘이 아래로 치우친 것 같음

**Comment by orgpark** [comment]
#316

**Comment by good2hear** [comment]
@kyo504 
1. placeholder 가 (vertically) 중앙으로 오는건 iOS 에서는 안되고 android 에서만 됩니다 (textAlignVertical)
2. 곡 설명 부분 높이가 텍스트 컨텐츠만큼 업데이트 되었으면 좋겠다는 부분은 곡 설명 부분이랑 곡 올리기 버튼 사이의 간격 말씀이신건가요?

**Comment by kyo504** [comment]
1. 그걸 `textAlign: vertical`을 안쓰고 할 수 있는 방법은 없나? 그냥 한줄로 해 놓고 contents 사이즈가 변경되면 높이를 업데이트 하는건 어떤가? 이건 설정 > 문의하기 가보면 어떻게 되어있나 볼 수 있어
2. 1번이랑 같은 얘기임~ 스크롤 안에 스크롤을 넣는 것 보다 1번 같은 형태가 어떤가 해서

**Comment by good2hear** [comment]
넵!! 한번 적용해보고 PR 올릴게요~

**Comment by good2hear** [comment]
완료
