### ISSUE TITLE
Mini Player에서 재생시 표시방법

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#313]
### Issue Description
1. 미니플레이어의 프로그레스바가 너무 작음
2. 플레이되고 있는 곡의 플레이버튼이 그대로 살아있음

![img_4491](https://cloud.githubusercontent.com/assets/3348009/20952186/fa690bec-bc6d-11e6-81b7-29ecb3cf6862.jpg)

### Steps to Reproduce

Step 1: 홈화면에서 최신곡 선택

### Expected Results
1. 미니플레이어의 프로그레스바를 미니플레이어의 상단으로 위치시키고 크기를 조금 더 키웠으면 함
2. 플레이되고 있는 곡의 플레이 버튼을 pause로 바꾸건지 혹은 Player가 돌고 있는 gif로 변경 필요하지 않나 싶음

### Additional Information
http://loading.io/ 에서 하나 만들어 쓰면 되지 않을까 싶음. (svg로도 가능하고 슬랙에 하나 붙여놨음)

**Comment by kyo504** [comment]
1. 높이는 조정했음
2. 해당 아이콘은 변경 되는게 아님

**Comment by kyo504** [comment]
1. 색상 및 프로그래스바 위치는 디자인너와 조정해서 반영된 사항이니 목요일에 추가적으로 모였을 때 다시 논의 하면 될 듯
2. 해당 위치에 있는 플레이 아이콘은 이 곡을 누르면 플레이가 된다는 것을 사용자에게 알려주기 위함이고 현재 이 곡이 플레이되고 있다는 걸 알려주기 위한 용도가 아님

**Comment by kyo504** [comment]
1번은 최신에서 확인해보면 되고 2번은 일단 현재 상태 유지. 혹시 이견이 있다면 의견 남겨주거나 re-open 해줘
