### ISSUE TITLE
곡 올리기에서의 텍스트

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#316]
### Issue Description
무엇을 입력해야 하는지가 표시되고 constraint가 표시가 되어야 함

### Steps to Reproduce

Step 1: 곡올리기 터치

### Expected Results
가사입력 창: 
가사를 입력해주세요. (가사를 입력하지 않으면 피드백을 받지 못할 수 있습니다.)
여러명이 곡에 참여한 경우 해당부분의 가사에 참여자 이름을 반드시 적어주세요.

곡 설명:
이 곡은 어떤 곡인가요? 곡에 대해 설명해주세요. 멘토에게 궁금한 점도 적어주세요.

### Actual Results
현재는 X자 이상 입력해주세요 라고만 나옴

### Additional Information

![image](https://cloud.githubusercontent.com/assets/3348009/20957699/a1273352-bc94-11e6-9655-4ccd42cfd6ff.png)

**Comment by good2hear** [comment]
완료
