### ISSUE TITLE
Header 컴포넌트 더보기 padding 늘리기

### ISSUE THREAD

**Issue by good2hear** [AllThatSeries/fym_mobile#318]
### Issue Description
Header 에서 더보기 누르면 한번에 잘 안눌릴때가 많음

### Steps to Reproduce

Step 1: 앱 실행
Step 2: Header 안 오른쪽에 있는 더보기 클릭

### Expected Results
더보기를 누르면 바로 인식

### Actual Results
한번에 인식 안되는 경우 많음 

### Additional Information
오른쪽에는 padding 이 끝까지 있고, 왼쪽에만 padding 추가하면 될 듯함

**Comment by kyo504** [comment]
수정 완료
