### ISSUE TITLE
멘토정보 null

### ISSUE THREAD

**Issue by orgpark** [AllThatSeries/fym_mobile#330]
### Issue Description
멘토정보 null인경우가 발견됨

### Steps to Reproduce

Step 1: reflow 혹은 yoohyun이 피드백 준 곡을 찾아서
Step 2: 곡정보 클릭
Step 3: 멘토 선택

### Expected Results
멘토의 이름이 표시되어야 함. 예) 'YOOHYUN' 의 피드백

### Actual Results
null의 피드백

### Additional Information
![image](https://cloud.githubusercontent.com/assets/3348009/21036310/5658e940-be08-11e6-9532-fc9b2888887c.png)

**Comment by good2hear** [comment]
완료
