### ISSUE TITLE
sticky mini player 에서 곡 제목을 클릭해서 재생하려고 하면 currentTime 부분이 NaN 이 뜸 

### ISSUE THREAD

**Issue by good2hear** [AllThatSeries/fym_mobile#86]

**Comment by good2hear** [comment]
요 이슈도 #87 이 발생할때 늘 같이 발생했고.. 
검은화면없이 NaN 만 뜰 때도 있었습니다. 

두건 모두 sticky mini player 에서 play 하다가 발생한 이슈 입니다.

**Comment by kyo504** [comment]
@good2hear Android 에서 했을 때는 해당 증상을 본적이 없네. 현재도 재현된다면 관련 내용 기술해주고 만약 없으면 일단 닫고 나중에 발생하면 다시 보자.
