### ISSUE TITLE
player 바탕화면이 검은색으로 나오는 현상 

### ISSUE THREAD

**Issue by good2hear** [AllThatSeries/fym_mobile#87]
### Issue Description

player 바탕화면이 검은색으로 나오는 현상

### Steps to Reproduce

Step 1:
Step 2:
...

**Comment by kyo504** [comment]
@good2hear 위에 내용 확인해서 업데이트하고 알려줘

**Comment by good2hear** [comment]
<img width="361" alt="2016-09-23 12 56 55" src="https://cloud.githubusercontent.com/assets/8426267/18755870/a9b89fe4-8128-11e6-9148-72ff86b4f748.png">

## Steps to Reproduce 

Step 1: 메인화면 들어가서 Sticky mini player 클릭 
Step 2: player 가 뜨면 왼쪽 상단버튼 눌러서 메인화면으로 
Step 3: 다시 sticky mini player 클릭
Step 4: player play 
Step 5: player pause

Step 1 에서 Step 5 까지 갔을때도 있었고, Step 2, 3 skip 하고 바로 play pause 해봤을때도 이런적이 있었습니다.

지금은 이렇게 계속 해봐도 reproduce 가 안되네요 
(혹시 저는 이제 앱을 지우고 xcode를 통해서만 돌려서 그런건지도 모르겠네요..)

낼 한번 앱으로 해봐주세요~

**Comment by kyo504** [comment]
@good2hear Android 에서 했을 때는 해당 증상을 본적이 없네. 현재도 재현된다면 관련 내용 기술해주고 만약 없으면 일단 닫고 나중에 발생하면 다시 보자.
